My follow along code and notes for xarray lesson [here](https://earth-env-data-science.github.io/lectures/xarray/xarray.html)

# Xarray Fundamentals 

## Xarray Data Structures
xarray has **two** fundamental data structures:
* `DataArray` - *single* multi-dimensional variable and coordinates
* `DataSet` - *multiple* multi-dimensional variables that may or may not share the same coordinates

## DataArray
`DataArray` has **four** main attributes:
* `values` - `np.ndarray` with array's value
* `dims` - dimension name for each axis of array (e.g., (`'x'`, `'y'`, `'z'`))
* `coords` - dictionary-like container of arrays labeling each point
* `attrs` - an `OrderedDict` holding arbitrary metadata

In [1]:
import numpy as np
import xarray as xr
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
# Init array of values
arr = [9, 0, 2, 1, 0]

In [3]:
# Initialize simple DataArray - no dim or coords
da = xr.DataArray(arr)
da

<xarray.DataArray (dim_0: 5)>
array([9, 0, 2, 1, 0])
Dimensions without coordinates: dim_0

In [4]:
# Add dimension name
da = xr.DataArray(arr, dims = ['x'])
da

<xarray.DataArray (x: 5)>
array([9, 0, 2, 1, 0])
Dimensions without coordinates: x

In [5]:
# Add coordinate
da = xr.DataArray(arr,
                  dims = ['x'],
                  coords = {'x' : [10, 20, 30, 40, 50]}
                  )
da

<xarray.DataArray (x: 5)>
array([9, 0, 2, 1, 0])
Coordinates:
  * x        (x) int32 10 20 30 40 50

In [6]:
# Coordinate created *index*; similar to Pandas indexing
da.indexes

Indexes:
    x        Int64Index([10, 20, 30, 40, 50], dtype='int64', name='x')

## Multidimensional DataArray

In [ ]:
import pooch
url = "https://www.ldeo.columbia.edu/~rpa/float_data_4901412.zip"
files = pooch.retrieve(url, processor=pooch.Unzip(), known_hash="2a703c720302c682f1662181d329c9f22f9f10e1539dc2d6082160a469165009")
files

In [38]:
T = np.load(files[0])
S = np.load(files[1]).reshape(-1, 1).shape
date = np.load(files[2])
lon = np.load(files[3])
levels = np.load(files[4])
P = np.load(files[5])
lat = np.load(files[6])

In [39]:
salinity = xr.DataArray(
    S,
    dims = ['level', 'date'],
    coords = {
        'level' : levels,
        'date' : date
    },
)

ValueError: different number of dimensions on data and dims: 0 vs 2